site_name: Tally Hub
site_description: Professional Tally Light System for Video Production - Cost-effective, modern, and open-source tally lights for OBS Studio, vMix, and more
site_url: https://tallyhubpro.github.io/Tallyhub
repo_url: https://github.com/tallyhubpro/Tallyhub
repo_name: tallyhubpro/Tallyhub
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Tally Hub Contributors

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

  logo: assets/logo.svg
  favicon: assets/favicon.svg

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tallyhubpro/Tallyhub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tallyhubpro

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Features: features.md
  - Download: download.md
  - Getting Started:
    - Quick Start: getting-started/index.md
    - Complete Setup: getting-started/complete-setup.md
    - Installation Guide: getting-started/quick-start.md
    - Firmware Flashing: getting-started/firmware-flashing.md
  - Hardware:
    - Overview: hardware/index.md
    - Supported Devices: hardware/supported-devices.md
  - Video Mixers:
    - Supported Mixers: mixers/supported-mixers.md
  - User Guide:
    - Admin Panel: admin-panel.md
    - Troubleshooting: troubleshooting.md
