name: Build and Deploy MkDocs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  # Build and Deploy job
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        pip install mkdocs-material
        pip install pymdown-extensions
        
    - name: Build with MkDocs
      run: mkdocs build --clean
      
    - name: Deploy to tallyhubpro.github.io
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        personal_token: ${{ secrets.PAGES_DEPLOY_TOKEN }}
        external_repository: tallyhubpro/tallyhubpro.github.io
        publish_branch: main
        publish_dir: ./site
